#!/usr/bin/env bash
#This loop prints  fizz when a multiple of 3 and buzz when a multiple of 5. And fizzbuzz if a multiple of both
for ((i=1; i<=100; i++))
do
    if ((i % 3 == 0)) && ((i % 5 == 0)); then
        echo "FizzBuzz"
    elif ((i % 3 == 0)); then
        echo "Fizz"
    elif ((i % 5 == 0)); then
        echo "Buzz"
    else
        echo $i
    fi
done
