#!/usr/bin/env bash
#This a script that displays the content of /etc/passwd
while IFS=":" read -r username _ userid _ homedir _
do
    echo "Username: $username"
    echo "User ID: $userid"
    echo "Home Directory: $homedir"
done < "/etc/passwd"
