#!/usr/bin/env bash
#This uses a loop to print a text multiple times and pint another different text on the 9th line.
i=1
while [ $i -lt 10 ]
do 
    if [ $i -eq 9 ]  
   then 
echo "Best School"
echo "Hi"
    else
echo "Best School"
 
    fi
i=$((i+1))

done  
