#!/usr/bin/env bash
#This loops through text and prints different text on line 4 and 8
i=1
while [ $i -lt 11 ]
 do 
    if [ $i -eq 4 ]
    then
 echo "bad luck"
 elif [ $i -eq 8 ]
  then
  echo "good luck"
 else 
echo "Best School"
 fi 
i=$((i+1))
done
