#!/usr/bin/env bash
#This loop prints from 0:00 to 12:59
minutes=1
hours=0
while [ $hours -lt 13 ]; do
    echo Hour: $hours
    while [ $minutes -lt 60 ]; do
        echo $minutes
        (( minutes+=1 ))
    done
    (( minutes=1 ))
    (( hours+=1 ))
done
This is the answer
